apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: buildNodeApp
  annotations:
    alauda.io/displayName.zh-CN: 构建NodeApp
    alauda.io/displayName.en: Build NodeApp
    alauda.io/description.zh-CN: 构建NodeApp
    alauda.io/description.en: Build NodeApp
    alauda.io/readme.zh-CN: Nodejs
    alauda.io/readme.en: Nodejs
    alauda.io/version: v0.3
  labels:
    catgory: CI
    platform: Nodejs
    user: lq
    target: frontend
    fix: fix v1
    wide: china
spec:
    engine: graph
    withSCM: true
    stages:
      - name: Clone
        tasks:
          - name: Clone0
            type: public/clone
      - name: BuildImage
        tasks:
          - name: BuildImage
            type: public/alaudaBuildImage
            options:
              timeout: 3600
      - name: PushImage
        tasks:
          - name: firstPush
            type: public/push
            options:
              timeout: 3600
          - name: secondPush
            type: public/push
            options:
              timeout: 3600
          - name: thirdPush
            type: public/push
            options:
              timeout: 3600
      - name: test
        tasks:
          - name: test
            type: testorg001/test
            options:
              timeout: 3600
      - name: deploy
        tasks:
          - name: deploy
            type: testorg001/deploy
            options:
              timeout: 3600              
    arguments:
      - displayName:
          zh-CN: "基本信息"
          en: "Basic Info"
        items:
          - name: "dockerfilePath"
            schema:
              type: string
            binding:
              - BuildImage.args.dockerfilePath
            display:
              type: string
              name:
                zh-CN: "Dockerfile路径"
                en: "Dockerfile's path"
            required: true
default: ./
